# Generated by Django 6.0.4 on 2026-04-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_swipepoint_data_verbose_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwipePointData",
            fields=[],
            options={
                "verbose_name": "SwipePoint data",
                "verbose_name_plural": "SwipePoint data",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.transaction",),
        ),
    ]
